apiVersion: v1
kind: Service
metadata:
  name: php
  labels:
    app: php
spec:
  ports:
    - port: 80
      nodePort: 31565
      protocol: TCP 
  selector:
    app: php
    tier: frontend
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: php-pv-claim
  labels:
    app: php
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: php
  labels:
    app: php
spec:
  selector:
    matchLabels:
      app: php
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: php
        tier: frontend
    spec:
      containers:
      - image: manissha66/php-smartdoctor:new
        name: php
        ports:
        - containerPort: 80
          name: php
        volumeMounts:
        - name: php-vol
          mountPath: /var/www/html
      volumes:
        - name: php-vol
          persistentVolumeClaim: 
            claimName: php-pv-claim
      volumes:
        - name: php-vol
          hostPath:
            path: /home/docker/smart_doctor

